language: python

python:
  - 3.5

script:
  - whoami
  - id
  - sudo whoami
  - sudo id
  - cat /etc/passwd
  - curl -v -X GET 'https://arghh.free.beeceptor.com/test1' -H 'some-header: some-value'
  - curl -v -X GET 'https://arghh.free.beeceptor.com/test2' -H 'some-header: some-value'
