dist: xenial
language: python

python:
  - 3.6

script:
  - git clone https://github.com/codingo/Interlace.git
  - ls -al 
  - cd Interlace
  - ls -al
  - sudo snap install docker
  - docker run hello-world

